# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
  option: value
# output configuration options
output:
  # See the dedicated "output" documentation section.
  option: value
# All available settings of specific linters.
linters-settings:
  # See the dedicated "linters-settings" documentation section.
  option: value
linters:
  # See the dedicated "linters" documentation section.
  option: value
  enable-all: true
  disable:
    - exhaustivestruct # The owner seems to have abandoned the linter.  Replaced by exhaustruct.
    - scopelint # The repository of the linter has been deprecated by the owner.  Replaced by exportloopref
    - golint # The repository of the linter has been archived by the owner.  Replaced by revive.
    - maligned # The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment
    - interfacer # The repository of the linter has been archived by the owner.
    - deadcode # is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    - structcheck # is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    - nosnakecase # is deprecated (since v1.48.1) due to: The repository of the linter has been deprecated by the owner. Replaced by revive(var-naming).
    - ifshort # is deprecated (since v1.48.0) due to: The repository of the linter has been deprecated by the owner.
    - varcheck # is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    - structcheck # is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
    - varnamelen # useless in the scope of this project
    - gofumpt # useless in the scope of this project
    - gci # useless in the scope of this project
    - depguard # the linter began to behave strangely, suddenly began to mark imports that had previously been validated. Disconnected until the reasons are clarified
issues:
  # See the dedicated "issues" documentation section.
  option: value
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:    # Exclude `lll` issues for long lines with `go:generate`.
    - path: internal/oapi/
      linters:
        - lll
severity:
  # See the dedicated "severity" documentation section.
  option: value
