// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	slack "woodpecker/internal/services/slack"

	mock "github.com/stretchr/testify/mock"
)

// ChatBot is an autogenerated mock type for the ChatBot type
type ChatBot struct {
	mock.Mock
}

// GetMessages provides a mock function with given fields: inMsgChannel
func (_m *ChatBot) GetMessages(inMsgChannel chan slack.Message) {
	_m.Called(inMsgChannel)
}

// SendMessage provides a mock function with given fields: msg
func (_m *ChatBot) SendMessage(msg slack.OutMessage) {
	_m.Called(msg)
}

type mockConstructorTestingTNewChatBot interface {
	mock.TestingT
	Cleanup(func())
}

// NewChatBot creates a new instance of ChatBot. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChatBot(t mockConstructorTestingTNewChatBot) *ChatBot {
	mock := &ChatBot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
