// Code generated by mockery v2.20.0. DO NOT EDIT.

package userstatemanager_test

import (
	models "woodpecker/internal/models"

	mock "github.com/stretchr/testify/mock"

	structlog "github.com/powerman/structlog"
)

// StateHandler is an autogenerated mock type for the StateHandler type
type StateHandler struct {
	mock.Mock
}

// SendMessageByState provides a mock function with given fields: user, messengerToken, msg, log
func (_m *StateHandler) SendMessageByState(user models.User, messengerToken models.UserMessengerToken, msg string, log *structlog.Logger) {
	_m.Called(user, messengerToken, msg, log)
}

type mockConstructorTestingTNewStateHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewStateHandler creates a new instance of StateHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStateHandler(t mockConstructorTestingTNewStateHandler) *StateHandler {
	mock := &StateHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
