// Code generated by mockery v2.20.0. DO NOT EDIT.

package chatservice_test

import (
	chatservice "woodpecker/internal/services/chat"

	mock "github.com/stretchr/testify/mock"

	structlog "github.com/powerman/structlog"
)

// ChatService is an autogenerated mock type for the ChatService type
type ChatService struct {
	mock.Mock
}

// StartChat provides a mock function with given fields: chatBot, log
func (_m *ChatService) StartChat(chatBot chatservice.ChatBot, log *structlog.Logger) error {
	ret := _m.Called(chatBot, log)

	var r0 error
	if rf, ok := ret.Get(0).(func(chatservice.ChatBot, *structlog.Logger) error); ok {
		r0 = rf(chatBot, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewChatService interface {
	mock.TestingT
	Cleanup(func())
}

// NewChatService creates a new instance of ChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChatService(t mockConstructorTestingTNewChatService) *ChatService {
	mock := &ChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
