on:
  push:
    branches:
      - main
  pull_request:

name: Test
jobs:
  lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.5.3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.5
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out
        uses: actions/checkout@v3.5.3
      - name: go test
        run: go test -v -race -coverprofile=profile.cov ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1.7.0
        with:
          path-to-profile: profile.cov
